image: node:latest

stages:
  - staging

deploy_stage:
  stage: staging
  only:
    - staging
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - apt-get install -qq openssh-client # Install OpenSSH client
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config # Disable strict host key checking
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PVT_KEY" | ssh-add - # Add SSH key directly without eval
  script: ssh -p $PORT $SSH_USER@$SERVER_IP "cd dev/workitpt-api && sudo chmod +x build* && ./build_stag.sh && exit"
